name: release-gate

on:
  # temporary, only for testing this release gate file
  push:
    branches: [ci/release-gate]
    paths:
      - 'clean-architecture-visualizer/**'
      - '.github/workflows/release-gate.yml'
  workflow_dispatch:

jobs:
  verify-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show workspace after checkout
        run: ls -la

      - uses: ./.github/actions/setup-node-env
        with:
          working-directory: ./clean-architecture-visualizer

      - name: Build the CLI and frontend
        run: npm run build
        working-directory:  ./clean-architecture-visualizer
      
      - name: pack then install package
        run: npm pack && npm install -g ./*.tgz
        working-directory: ./clean-architecture-visualizer

      - name: check cave version
        run: cave --version